# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
ilr_basis <- function(dim) {
    .Call('_coda_dist_ilr_basis', PACKAGE = 'coda.dist', dim)
}

#' @export
ilr_coordinates <- function(X) {
    .Call('_coda_dist_ilr_coordinates', PACKAGE = 'coda.dist', X)
}

#' @export
inv_ilr_coordinates <- function(ilrX) {
    .Call('_coda_dist_inv_ilr_coordinates', PACKAGE = 'coda.dist', ilrX)
}

#' @export
ilr_to_alr <- function(ILR) {
    .Call('_coda_dist_ilr_to_alr', PACKAGE = 'coda.dist', ILR)
}

#' @export
alr_to_ilr <- function(ALR) {
    .Call('_coda_dist_alr_to_ilr', PACKAGE = 'coda.dist', ALR)
}

#' @export
ddm <- function(x, alpha) {
    .Call('_coda_dist_ddm', PACKAGE = 'coda.dist', x, alpha)
}

#' @export
c_dm_fit <- function(X, eps = 0.0001, maxiter = 5000L) {
    .Call('_coda_dist_c_dm_fit', PACKAGE = 'coda.dist', X, eps, maxiter)
}

#' @export
c_dm_fit_alpha <- function(X, eps = 0.0001, maxiter = 5000L) {
    .Call('_coda_dist_c_dm_fit_alpha', PACKAGE = 'coda.dist', X, eps, maxiter)
}

#' @export
validate_dnm <- function(x, mu, sigma, order) {
    .Call('_coda_dist_validate_dnm', PACKAGE = 'coda.dist', x, mu, sigma, order)
}

#' @export
dnm <- function(x, mu, sigma, order) {
    .Call('_coda_dist_dnm', PACKAGE = 'coda.dist', x, mu, sigma, order)
}

#' @export
m1_dnm <- function(x, mu, sigma, order) {
    .Call('_coda_dist_m1_dnm', PACKAGE = 'coda.dist', x, mu, sigma, order)
}

#' @export
m2_dnm <- function(x, mu, sigma, order) {
    .Call('_coda_dist_m2_dnm', PACKAGE = 'coda.dist', x, mu, sigma, order)
}

#' @export
hermite_integration <- function(order, d) {
    .Call('_coda_dist_hermite_integration', PACKAGE = 'coda.dist', order, d)
}

#' @export
gaussian_hermite <- function(order, mu, sigma) {
    .Call('_coda_dist_gaussian_hermite', PACKAGE = 'coda.dist', order, mu, sigma)
}

#' @export
hermite <- function(order) {
    .Call('_coda_dist_hermite', PACKAGE = 'coda.dist', order)
}

#' @export
lpnm_join_no_constant <- function(x, mu, inv_sigma, p, h) {
    .Call('_coda_dist_lpnm_join_no_constant', PACKAGE = 'coda.dist', x, mu, inv_sigma, p, h)
}

#' @export
expected_hermite <- function(x, mu_ilr, sigma_ilr, order) {
    .Call('_coda_dist_expected_hermite', PACKAGE = 'coda.dist', x, mu_ilr, sigma_ilr, order)
}

#' @export
expected_montecarlo_01 <- function(x, mu_ilr, sigma_ilr, Z, mu_exp) {
    .Call('_coda_dist_expected_montecarlo_01', PACKAGE = 'coda.dist', x, mu_ilr, sigma_ilr, Z, mu_exp)
}

#' @export
expected_montecarlo_centered <- function(x, mu_ilr, sigma_ilr, Z, mu_exp) {
    .Call('_coda_dist_expected_montecarlo_centered', PACKAGE = 'coda.dist', x, mu_ilr, sigma_ilr, Z, mu_exp)
}

#' @export
expected_montecarlo_02 <- function(x, mu_ilr, sigma_ilr, Z, mu_exp, var_exp) {
    .Call('_coda_dist_expected_montecarlo_02', PACKAGE = 'coda.dist', x, mu_ilr, sigma_ilr, Z, mu_exp, var_exp)
}

#' @export
expected_montecarlo_03 <- function(x, mu_ilr, sigma_ilr, Z, mu_sampling, sigma_sampling) {
    .Call('_coda_dist_expected_montecarlo_03', PACKAGE = 'coda.dist', x, mu_ilr, sigma_ilr, Z, mu_sampling, sigma_sampling)
}

#' @export
expected_montecarlo_04 <- function(x, mu_ilr, sigma_ilr, Z, m1, m2) {
    .Call('_coda_dist_expected_montecarlo_04', PACKAGE = 'coda.dist', x, mu_ilr, sigma_ilr, Z, m1, m2)
}

#' @export
expected_metropolis <- function(x, mu_ilr, sigma_ilr, mu_exp, nsim, ignored_steps = 100L) {
    .Call('_coda_dist_expected_metropolis', PACKAGE = 'coda.dist', x, mu_ilr, sigma_ilr, mu_exp, nsim, ignored_steps)
}

#' @export
metropolis_sample <- function(x, mu_ilr, sigma_ilr, x0, nsim, ignored_steps = 100L) {
    .Call('_coda_dist_metropolis_sample', PACKAGE = 'coda.dist', x, mu_ilr, sigma_ilr, x0, nsim, ignored_steps)
}

mvf_deriv <- function(I, a, mu, inv_sigma, x) {
    .Call('_coda_dist_mvf_deriv', PACKAGE = 'coda.dist', I, a, mu, inv_sigma, x)
}

mvf_deriv2 <- function(I, J, a, mu, inv_sigma, x) {
    .Call('_coda_dist_mvf_deriv2', PACKAGE = 'coda.dist', I, J, a, mu, inv_sigma, x)
}

#' @export
alr_basis <- function(K) {
    .Call('_coda_dist_alr_basis', PACKAGE = 'coda.dist', K)
}

#' @export
mvf_maximum <- function(x, mu_ilr, sigma_ilr, B, eps, max_iter, prop) {
    .Call('_coda_dist_mvf_maximum', PACKAGE = 'coda.dist', x, mu_ilr, sigma_ilr, B, eps, max_iter, prop)
}

#' @export
ldnormal <- function(H, mu, inv_sigma) {
    .Call('_coda_dist_ldnormal', PACKAGE = 'coda.dist', H, mu, inv_sigma)
}

#' @export
lpmultinomial_const <- function(x) {
    .Call('_coda_dist_lpmultinomial_const', PACKAGE = 'coda.dist', x)
}

#' @export
lpmultinomial <- function(x, p, lconst) {
    .Call('_coda_dist_lpmultinomial', PACKAGE = 'coda.dist', x, p, lconst)
}

#' @export
lpnm_join <- function(x, mu, inv_sigma, P, H) {
    .Call('_coda_dist_lpnm_join', PACKAGE = 'coda.dist', x, mu, inv_sigma, P, H)
}

#' @export
lpmultinomial_mult <- function(P, x) {
    .Call('_coda_dist_lpmultinomial_mult', PACKAGE = 'coda.dist', P, x)
}

